BBBB BBBB BBBBBBBBBB

BB BBBBBBB
XXXX gettext(u'Home') XXXXX
BBBB
BBB BBBB BB BBBBBBBBBBB

    BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBXX gettext(u'Home') XXXX
    XXXXX
    BBBBB

    BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BB BBBBBBBBBBBBBBB
    XXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
    BBBB
    XXX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX
    XXXXX
    BBBBB
    BB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB
    BBBBB

BBBBBB
BBBBB
