BBBB BBBB BBBBBBBBBB

BBBBBBBBB
BB BBBBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	BBB BBBB BB BBBBBBBBBBB

    BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
	XXX XXXXXXXXXXXXBB BBBBBBB XXXXXXBBBBBX
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
	    XX XXXXXXBBB BBBBBBXX gettext(u'Home') XXXX
	XXXXX
	BBBBB

	BB BBBBBBBBBBBB
	XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBB
        BB BBB BBBBBBBBB BBB BBBBBBBBBBBBB XXXXXBBBBB
        BB BBBBBBBBBBBB XXXXBBBBBX
        XXXXXXXXXXXXXXXXXXXXXXX
		XX XXXXXXXXXXXX
		
		BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBBB
		BBBBBBBBB BBBB
		BBBBB
	XXXXX
    BBBBB

	BBBBBB
XXXXX
BBBBB
BBBBBBBBBBBB
