BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBB BBBB BBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB BBBBBBBBB BB BBBB
BBB BBB BB BBBBBB BBB BBBBBBBBBBBBBX BBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBBBBBBBBBBBBBBBBBB

BBBBB BBBBB
BBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBB

XXX XXXXXXXXXXXXXXXXXXXX
BBBBBBBB

BBBBB BBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXXXXXXXXX
     gettext(u'Posted by') X
    BBBB BBBBBBBBBBBBBB BB BBBBBB
    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBXXFFFFFFFFFFFFFFFFFFFFFFFXXXX
    BBBBBBB
     gettext(u'%(sometime)s ago') SSSSSSSSSSSS SSS
XXXXX
BBBBBBBBBBB
BBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXX
    BB BBBBBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBB BBBBBBBBBXXBBBBBBBBB
                 gettext(u'Comments') 
            BBBBBBBBBBBBXXXXX
        BBBBXXX XXXXXXXXXXXXXXXXXBBBBBBBBB
             ngettext(u'%(comments_count)s comment', u'%(comments_count)s comments', count) SSSSSSSSSSSSSSSSSS SSSSSSSPPPPPPPPPPPPPPPPPP PPPPPPPP
            BBBBBBBBBBBBXXXXX
        BBBBB
    BBBBB
XXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBB BXXXXXX
BBBBB
BBBBBBBB

BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB BBBBBBBBBBBBBBBBB
FFFFFFFFFFFFFFFF
BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB BBBBBBBBB BB BBBB
BB BBBB
BBBBBBBBB
XXX XXXXXXXXXXXXXXXXXX XXXXXX
    XXXX gettext(u'Tags') XXXXXX
    BBB BBB BB BBBB
    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBXXXXXXBB BBB BBBBBBBBBBBBX BBBBBXXXXX
    BBBBBB
XXXXX
BBBBBBBBBBBB
BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB BBBBBBBBB
    XXXXXX
XXXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB BBBBBBBBB
XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFXXXXXXXXXXFFFFFFFFFXX gettext(u'Share on Twitter') XXXX
XX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Share on Facebook') XXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBB
XXX XXXXXXXXXXXXXX
BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBB
BB BBBBBBBB
XXX XXXXXXXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXX
XXXXX
BBBBB
BBBBBBB
BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
BB BBBB
XXX XXXXXXXXXXXXX
    XX XXXXXXXX XXXXXXXXXX
XXXXX
BBBBB
BBBBBBB
XXXXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
XXXX gettext(u'Related posts') XXXXX
XXX XXXXXXXXXXXXXXXXXXXXXX
BBB BBBB BB BBBBBBBBBBBBB
     XXXXXX XXXXXXXXXXXXXXXXX
BBBBBB
XXXXX
XXXXXX
BBBBB
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBB
BBBBBBBB

BBBBBBBB
