BBBB BBBB BBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBBBBBBBXX
    BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
    BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB
    BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFXX gettext(u'Admin') XXXX
    XX XXXXXXFFFFFFFFFFFFFFFFFFFFFFFFXXXX gettext(u'Log out') XXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX

