BBBB BBBB
BBBB BBBBBBBBBBBBBB

BBBBBBBBBB
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
BBBBBBBBBB
BBBBBBBBBBBBB

BBB BBBBB BB BBBBBBBBBBBBBBB
BB BBBBBBBBBBBBBBB

BBBB
XXXX XXXXXXXXXXXXXXXXX XXXXXX 
    BB BBBBBBBBBBBB XXXXXXXXXBBBBBXX
    BB BBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXBBBBB
    
    BB BBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXX
        BBB B BB BBBBBBBBBBBB
        BB BBB BBBBBBBBBBBBB X BBBBB
        BBBBBB
    XXXX
    BBBB BBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXXXX
    BBBB BBBBBBBBBBBBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXX gettext(u'required') XXXX
    BBBBB
XXXXXX
BBBBB
BBBBBB
