BBBB BBBBBBBBBBBBBB BBBBBBBBBBB BBBB

XXXXX XXXXXXXXXXXXX
    BB BBBBBBBBBBBBBB
     gettext(u'Current rating') X FFFFFFFFFFF
    BBBB
     gettext(u'Currently unrated') 
    BBBBB
XXXXXXX

BB BBB BBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXBBB BBBBBBBBXX
    BBBBBBBBBB
    BBBBBBBBBB
    BBBBBBBBBBBBB
    XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX gettext(u'Rate') X
        XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX
XXXXXXX
BBBBB
