BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBBBBBBB

BBBBB BBBBBBBBBB gettext(u'Classe inversée de M.GEORGET') BBBBBBBB
BBBBB BBBBB gettext(u'Classe inversée de M.GEORGET') BBBBBBBB

BBBBB BBBBBBBBBBBBBBB
XXX XXXXXXXXXXXXXXX gettext(u'Home') XXXXX
BBBBBBBB


BBBBB BBBBBBB
XXXX XXXXX X XXXXXXXXXXXXXXXX
XXXXXXXXX
  XXXXXXXXXX XXXX XXX XXXXXXX XXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XX XXXXXXX XXX XXXXXXX X XXXXXXXXX
XXXXX
XXXXX
  XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX

      XX XXXX X XXX XXXX XXXX XX XXXXXX XX XXXXXXXXX XXX XXXXXX XXXXXXX XX XXXXX XXX XXXX XXXXXXXX XXXX XXXXXXXXXX XX XX XXXXXXXXXXXXX XX XX XXXXX XXXX XXXX XX XX XXXX XXXXXXXXX XXXXX XX XX XXXXXXXXXX XXX XX XXXXXXXXX XX XXXXXXXXX XX XXXXXXXXXXXXXX XX XXXXXXX
      XXXXX
    XXXXX XXXXX X XXXXXX XXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB X XXXXXXXXXXXXX
    XXXXXXX
XXXXX
      XXXXXXX XXXXXXXXXXXXXX XX XXXX XX X XXXXXX X
XXXX
  XXXX
    XXXXXXXXXXXX XX XXXXXXX XXXXXXXX XX XXXXXX
    XXXXX
  XXXX
    XXXXXXXXXX XX XX XXXXX X XXXXXXXX XX XX XXXXX X XX XXXXXX XXX XXXXXX XXXXXXXX XX XXX XXX XXXXXXXX XXXX XX XXXXXX XX XX XXXXXXXXX XXX XXXXXXXXXXXXX XXXXX XXXXXXXXXXX X XXX XX XXXXXXXXXXXXX XX XXXXXXXX XXXXXXXXX
  XXXXX
XXXX
  XXXXXXXXX XXXXXXXXXXXXXXXXXXX XX XXXXXX
  XXXXX
XXXXX
XX XXX XX XXXXXX XXXXXXXX XXXX XXXXXXX XXXXXX XXXXX XXXXXX XXXXXXXXX XXX XXXXXXXX XXXXXXX XXXX XXXXXXX XXX XXXX XXXX XX XX XXXXXX XXXXXX XX XX XXXX XXXXXXX XX XXXXXXX
XXXXXX XXX XXXXXXXXX XXX XX XXXXXXXXXX XXXX XXXX XXXXXXX XXX XXXXXXXXXXX XX XX XXXX XXX XXXXXX XXXXX XXX XXXXXXXX
XXXXX
XXXXX
    XXXX
  XXXXXXXXXXXXX

  XXXX XXXXXXXXXXXXXXX

      XX XXXXX X XXXXXXXXX
        XXXX XXXXX X XXXXXXXX
          XXXX XXX X XBBBBBB BBBBBBBBBX XXXXX XXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX X XXXXX XXXXXXX XXXXXXXXX

        XXXXXX XXXXXXXXXX XX XXXXXXXXXXXXX XX XXXXXXX XX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXX
      XXXX

  XXXXXX

XXXXXXXXXX
XXXXXX
BBBBBBBB BBBBBBB
