XXXXXXXXX XXXXX
XXXXX XXXXXXXBB BBBBBBBBBBBBB XXXXXXXXXBBBBBX
BBBB BBBBBBBBBB BBBBBBBBBBBBBB BBBB BBBBBBBBBBB

XXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBB X BBBBBXXXXXXXX
XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX

BBBBBBBBBBB BBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBXX
BBBBBBBBBBBBBB

BBBBBBBB BBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXX
BB BBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
BBBBB
BBBBBBBBBBB BBBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXX
BB BBBBBBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
BBBBB
BBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBB
BBBBBBBBBBB

BBBBBBBB BB
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBB BBBBBBBBBBBBBBBB
BBBBBBBBBBB

XXXXXXX XX XX XXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXXXXXXX

BBBBB BBBBBBBBBBBBBBBBBB
XXXXXXX

XXXXX XXXXBBBBB BBBBBBBXXXXBBBBBBBBXX

XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXX gettext(u'Toggle Navigation') XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    BBBBB BBBBBBBBBBBB
    BB BBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXBBBBB
    BB BBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXBBBBB
    BBBBBBBB
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
XXXXXX
XXXXXX
XXXXXX XXX

XXXX XXXXXXXXXXXXXXXXXX

BBBBBBBBBB
BB BBBBBBBB
XXXX XXXXXXXXXXXXXXXXX
BBB BBBBBBB BB BBBBBBBB
XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
XXXXXX
BBBBBB
XXXXXX
BBBBB
BBBBBBBBBBBBB

XXXXBBBBB BBBBBBBBBBBBBXXXXX

XXX XXXXXXXXXXXXXXXXXXX
BBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBB
XXXXX

XXXXXX

XXXX XXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXX
    BBBBB BBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXX
    BBBBBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXX
    BBBBB BBBBBBBBBBBB
XXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXX
    BBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
    BBBBB BBBBBBBBBBB
    BBBBBBBBBBB BBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBB
    BBBBBBBBBBBBBB
    BBBBBBBB
    XXXXXX
    XXXXXX
XXXXXX

XXXXXX
XXXXXX

XXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX
BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

XXXX XXXXXXXXXXXX
XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
     gettext(u'Powered by') 
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBB BBBBBBBBBBBBBBX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBBBBBBBB
     gettext(u'and') 
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
     gettext(u'Theme by')  XX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXX
XXXXXX
XXXXXX
XXXXXXXXX

BBBBB BBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB

XXXXXXX
XXXXXXX
