BBBB BBBB BBBBBBBBBB
BBBBBBBBB
BB BBBBBBBBBBBBBBBBBBB

BB BBBBBBBBBBBB BB B
  XXXXXXX XXXXXXXXXXXX



    BBB BBBB BB BBBBBBBBBBB
    BB BBB BBBBBBBB BBB BBBBBBBBBBBBBBB BBB BBBBBBBBBBBBB
    XXBB BBBBBBB XXXXXXXXXXXXBBBBB XXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXX XXXXXXBBB BBBBBBXX gettext(u'Accueil') XXXX
    XXXX
    BBBBB
    BB BBBBBBBBBBBB
    XX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXBBBBB
               BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXBBBBBX
        XXXXXX
        XX XXXXXXXXXXXX XXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        BBBBBX
            
            BB BBBBBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXXXXXXXXXXXXBBBBB
        XXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB
    XXXX
    BBBBB
    BBBBBB

BBBB
XXX XXXXXXXXXXXXXXXXXXXXXX
    BBB BBBB BB BBBBBBBBBBB
    BB BBBBBBBBBBBB
    XXX XXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBB
               BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXBBBBBX
        XXXXXX
        XX XXXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBB
    XXXXX
    BBBBB
    BBBBBB
XXXXX

BBBBB

BBBBB
BBBBBBBBBBBB
XXXXX
  XX XXXXXXXXXXXXXXXXXXXXX
XXXXXX
  XXXXXXXXX
